
category: "juice_bottle" #"juice_bottle"#"splicing_connectors" #"breakfast_box" #"screw_bag"
histogram_type: "area"
image_size: 256
feature_list: ["cnn_image"]
max_hyper: 3.5
no_cluster: False
reduce_dim: True
proj_dim: 512
filter_hist: True 

use_grounding_filter: False
no_sam: False
grounding_config: 
  box_threshold: 0.3
  text_threshold: 0.3
  filter_by_combine: False
  text_prompt: "alcohol. apple juice. beverage. bottle. liquor. glass bottle. juice. lemonade. liquid. olive oil. orange juice. yellow banana. bottle. glass bottle. glass jar. jug. juice. liquid. milk beverage. bottle. cherry. condiment. liquor. glass bottle. honey. juice. liquid. maple syrup. sauce. syrup. tomato sauce."
  background_prompt: ""

sam_config:
  points_per_side: 32
  points_per_batch: 16
  pred_iou_thresh: 0.88
  stability_score_thresh: 0.96 #0.97
  stability_score_offset: 1.0
  box_nms_thresh: 0.7
  crop_n_layers: 1
  crop_nms_thresh: 0.7
  crop_overlap_ratio: 512 / 1500
  crop_n_points_downscale_factor: 1
  point_grids: None
  min_mask_region_area: 500
  output_mode: "binary_mask"